#指定当前有效的配置文件
spring:
  profiles:
    active: Dev

#应用名字
  application:
    name: groceryZuul

---
#服务注册中心端口号
server:
  port: 8771

spring:
  profiles: Dev
    #服务注册中心实例的主机名

eureka:
  instance:
    hostname: localhost

#服务注册中心的配置内容，指定服务注册中心的位置
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---
#服务注册中心端口号
server:
  port: 8772

spring:
  profiles: Test
    #服务注册中心实例的主机名

eureka:
  instance:
    hostname: localhost

#服务注册中心的配置内容，指定服务注册中心的位置
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/

---
#服务注册中心端口号
server:
  port: 8773

spring:
  profiles: Prd
    #服务注册中心实例的主机名
eureka:
  instance:
    hostname: localhost

#服务注册中心的配置内容，指定服务注册中心的位置
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8763/eureka/