#指定当前有效的配置文件
spring:
  profiles:
    active: Dev

#应用名字
  application:
    name: groceryZuul

#路由配置
zuul:
  routes:
    auth:
      #Spring Cloud系列之客户端请求带“Authorization”请求头,经过zuul转发后丢失了,所以将sensitive-headers置为空，将custom-sensitive-headers置为true
      sensitive-headers:
      custom-sensitive-headers: true
      #path来配置路由，serviceId配置路由到的服务
      path: /auth/**
      serviceId: groceryauth
    main:
      sensitive-headers:
      custom-sensitive-headers: true
      path: /main/**
      serviceId: grocerymain
    static:
      sensitive-headers:
      custom-sensitive-headers: true
      path: /static/**
      serviceId: grocerystatic

---
#服务注册中心端口号
server:
  port: 8771

spring:
  profiles: Dev
    #服务注册中心实例的主机名

eureka:
  instance:
    hostname: localhost

#服务注册中心的配置内容，指定服务注册中心的位置
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---
#服务注册中心端口号
server:
  port: 8772

spring:
  profiles: Test
    #服务注册中心实例的主机名

eureka:
  instance:
    hostname: localhost

#服务注册中心的配置内容，指定服务注册中心的位置
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/

---
#服务注册中心端口号
server:
  port: 8773

spring:
  profiles: Prd
    #服务注册中心实例的主机名
eureka:
  instance:
    hostname: localhost

#服务注册中心的配置内容，指定服务注册中心的位置
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8763/eureka/